
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/backend_api_db
    volumes:
      - .:/app

  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
